// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG0q6EOQJ9l5lIWoTORI7_myOjqlK9_X8',
    appId: '1:319337104794:web:1e509e264ce1a6c4f3e623',
    messagingSenderId: '319337104794',
    projectId: 'sams-965',
    authDomain: 'sams-965.firebaseapp.com',
    storageBucket: 'sams-965.firebasestorage.app',
    measurementId: 'G-FSG7R07LQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp1b5z7IbiZ_6GpPbKdmKGNjTAw6wKBIo',
    appId: '1:319337104794:android:c46343cf90941876f3e623',
    messagingSenderId: '319337104794',
    projectId: 'sams-965',
    storageBucket: 'sams-965.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClRfROgikJJVR9FzeJSu6pLk7AhMWP7ZI',
    appId: '1:319337104794:ios:efaa18224bb268aaf3e623',
    messagingSenderId: '319337104794',
    projectId: 'sams-965',
    storageBucket: 'sams-965.firebasestorage.app',
    iosBundleId: 'com.example.smas3',
  );
}
